name: AddTag
on: push
jobs:
  add_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: List Tags
        run: |
          date_now=$(date +"%Y.%m.%d")
          echo -e "${date_now}"
          git tag
